# Generated by Django 3.0.5 on 2020-05-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
