# Generated by Django 3.0.5 on 2020-05-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200518_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
